version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/input.csv
    outputs:
      highly_sensitive:
        dataset: output/input.csv

  data_preparation:
    run: stata-mp:latest analysis/data_preparation_and_descriptives.do
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        dataset: output/main.dta
        dataset2: output/descriptives.xlsx
      moderately_sensitive:
        log: logs/data_preparation.log
        output: output/descriptives.csv
        
  cox_regression:
    run: stata-mp:latest analysis/cox.do
    needs: [data_preparation]
    outputs:
      highly_sensitive:
        dataset: output/cox.xlsx
      moderately_sensitive:
        log: logs/cox.log
        figure1: output/psgraph.svg  
        output: output/cox.csv
