version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/input.csv
    outputs:
      highly_sensitive:
        dataset: output/input.csv

  data_preparation:
    run: stata-mp:latest analysis/data_preparation_and_descriptives.do
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        dataset: output/main.dta
        dataset2: output/descriptives.xlsx
      moderately_sensitive:
        log: logs/data_preparation.log
        output: output/descriptives.csv
        
  cox_regression:
    run: stata-mp:latest analysis/cox.do
    needs: [data_preparation]
    outputs:
      highly_sensitive:
        dataset: output/cox.xlsx
      moderately_sensitive:
        log: logs/cox.log
        output1: output/cox.csv
        figure1: output/phtest.svg 
        figure2: output/psgraph.svg 
       

  cox_subgroup:
    run: stata-mp:latest analysis/cox_subgroup.do
    needs: [data_preparation]
    outputs:
      highly_sensitive:
        dataset: output/cox_subgroup.xlsx
      moderately_sensitive:
        log: logs/cox_subgroup.log
        output: output/cox_subgroup.csv

  psw_check:
    run: stata-mp:latest analysis/psw_check.do
    needs: [data_preparation]
    outputs:
      highly_sensitive:
        dataset: output/psw_check.xlsx
      moderately_sensitive:
        log: logs/psw_check.log
        output: output/psw_check.csv



